#!/bin/bash

INPUT_JSON="$1"
if [ -z "$INPUT_JSON" ]; then
    echo "Please provide the metadata.json file path as first argument." 1>&2
    exit 1
fi

jq '{
    name: ("ypid/" + .name),
    type: "library",
    description: .description,
    keywords: .tags,
    homepage: .url,
    support: .support,
    license: .license_full,
    authors: .authors,
    # "autoload": {
    #     "psr-0" : {
    #         "SunCalc" : "lib"
    #     }
    # }
}' "$INPUT_JSON"
